# Generated by Django 3.2.9 on 2021-12-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_item_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(max_length=3000)),
            ],
        ),
    ]
