# Generated by Django 3.2.9 on 2021-12-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_url',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
