# Generated by Django 3.2.9 on 2021-12-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_file_url_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_url',
            name='user_id',
        ),
    ]
